[profile.default]
src = "test/src"
script = "test/script"
out = "test/out"
libs = ["test/lib", "lib", "/Users/tuxcanfly/Work/nitro-contracts/lib"]
remappings = [
  "forge-std=/Users/tuxcanfly/Work/nitro-contracts/lib/forge-std/src/",
  "@nitro-contracts=/Users/tuxcanfly/Work/nitro-dev/nitro-contracts/src/",
  "@openzeppelin/=/Users/tuxcanfly/node_modules/@openzeppelin/"
]
