[profile.default]
src = "src"
out = "out"
libs = ["dependencies", "lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true

[dependencies]
"@openzeppelin-contracts" = { version = "4.9.6" }
forge-std = { version = "1.7.6" }
"@nitro-contracts" = { version = "3.2.0", url = "https://github.com/OffchainLabs/nitro-contracts/archive/refs/tags/v3.2.0.zip" }
blobstream-contracts = { version = "3.1.0", url = "https://github.com/celestiaorg/blobstream-contracts/archive/refs/tags/v3.1.0.zip" }

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_location = "txt"
recursive_deps = true
